const ParkTopics = [
  "African American Heritage",
  "American Revolution",
  "Ancient Seas",
  "Animals",
  "Archeology",
  "Architecture and Building",
  "Arctic",
  "Arts",
  "Asian American Heritage",
  "Aviation",
  "Banking",
  "Birthplace",
  "Burial, Cemetery and Gravesite",
  "Canyons and Canyonlands",
  "Caves, Caverns and Karst",
  "Climate Change",
  "Coasts, Islands and Atolls",
  "Colonization and Settlement",
  "Commerce",
  "Dams",
  "Dunes",
  "Engineering",
  "Enslavement",
  "Estuaries and Mangroves",
  "Explorers and Expeditions",
  "Farming and Agriculture",
  "Fire",
  "Foothills, Plains and Valleys",
  "Forests and Woodlands",
  "Forts",
  "Fossils and Paleontology",
  "Geology",
  "Geothermal",
  "Glaciers",
  "Grasslands",
  "Great Depression",
  "Groundwater",
  "Hispanic American Heritage",
  "Immigration",
  "Impact Craters",
  "Incarceration",
  "Industry",
  "LGBTQ American Heritage",
  "Laborer and Worker",
  "Lakes",
  "Landscape Design",
  "Latino American Heritage",
  "Maritime",
  "Medicine",
  "Migrations",
  "Military",
  "Monuments and Memorials",
  "Mountains",
  "Music",
  "Native American Heritage",
  "Natural Sounds",
  "Night Sky",
  "Oceans",
  "Pacific Islander Heritage",
  "Presidents",
  "Reconstruction",
  "Religion and Spirituality",
  "River and Riparian",
  "Rock Landscapes and Features",
  "Scenic Views",
  "Schools and Education",
  "Science, Technology and Innovation",
  "Social Movements",
  "The Tropics",
  "Thickets and Shrublands",
  "Tragic Events",
  "Trails",
  "Transportation",
  "Unique Species",
  "Urban America",
  "Volcanoes",
  "Wars and Conflicts",
  "Waterfalls",
  "Watersheds",
  "Westward Expansion",
  "Wetlands",
  "Wilderness",
  "Women's History",
];

const ParkActivites = [
  "Arts and Culture",
  "Astronomy",
  "Auto and ATV",
  "Biking",
  "Boating",
  "Camping",
  "Canyoneering",
  "Caving",
  "Climbing",
  "Compass and GPS",
  "Dog Sledding",
  "Fishing",
  "Flying",
  "Food",
  "Golfing",
  "Guided Tours",
  "Hands-On",
  "Hiking",
  "Horse Trekking",
  "Hunting and Gathering",
  "Ice Skating",
  "Junior Ranger Program",
  "Living History",
  "Museum Exhibits",
  "Paddling",
  "Park Film",
  "Playground",
  "SCUBA Diving",
  "Shopping",
  "Skiing",
  "Snorkeling",
  "Snow Play",
  "Snowmobiling",
  "Snowshoeing",
  "Surfing",
  "Swimming",
  "Team Sports",
  "Tubing",
  "Water Skiing",
  "Wildlife Watching",
];
